const express = require('express');
const router = express.Router();
const productoController = require('../controllers/productController');
const { authenticateToken, authorize, ROLES } = require('../middlewares/auth');
const multer = require('multer');
const upload = multer({ storage: multer.memoryStorage() });
router.post('/', authenticateToken, authorize(ROLES.ADMINISTRADOR), upload.any(), productoController.createProducto);
router.get('/', productoController.getAllProductos);
router.get('/filters', productoController.getAllFilters);
router.get('/eliminados',authenticateToken, authorize(ROLES.ADMINISTRADOR), productoController.getDeletedProductos);
router.get('/:id', productoController.getProductoById);
router.put('/:id', authenticateToken, authorize(ROLES.ADMINISTRADOR), productoController.updateProducto);
router.patch('/:id/restore',authenticateToken, authorize(ROLES.ADMINISTRADOR), productoController.restoreProducto);
router.delete('/:id',authenticateToken, authorize(ROLES.ADMINISTRADOR), productoController.deleteProducto);
module.exports = router;